name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - action-demo
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: action-demo
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls

      - run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: set run name
        run: |
          MY_RUN_NAME="testName"
          echo "::set-env name=MY_RUN_NAME::$MY_RUN_NAME"

      - name: use custom variables
        run: |
          echo "using $var in action name"
          echo "using $frac in action name"

      - run: echo "link to this specific action is https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - run: echo "link to this specific action (in plain shell) is https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
